# Generated by Django 5.0.4 on 2024-04-08 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=10)),
                ('lname', models.CharField(max_length=10)),
                ('mobile_number', models.IntegerField()),
                ('venue', models.CharField(max_length=10)),
                ('date', models.DateField()),
                ('address', models.CharField(max_length=10)),
            ],
        ),
    ]
